if: tag IS blank
branches:
  only:
    - master
    - develop

language: node_js
node_js:
  - 16

cache: yarn

install:
  - yarn install

script:
  - echo "No tests ran"

before_deploy:
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install

deploy:
  - provider: script
    script: ./.travis/deploy
    skip_cleanup: true
    on:
      branch:
        - master
        - develop
